# Data Cleaning Advisor

In [24]:
import pandas as pd

advisor = pd.read_csv("../Data/sanlam_raw_advisors.csv") 

advisor.head(20)

,source_row_id,advisor_id,advisor_name,fsp_number,channel,network_name,province,active_flag
0,SA-0000001,ADV000001,Mariam Khumalo,SIM-FSP-000001,Bank Assurance,Metro Group,Gauteng,1
1,SA-0000002,ADV000002,Fatima Khumalo,SIM-FSP-000002,Bank Assurance,Coastal Network,Northern Cape,N
2,SA-0000003,ADV000003,Ayanda Ndlovu,SIM-FSP-000003,Bank-Assurance,North Network,Limpopo,N
3,SA-0000004,ADV000004,Ayanda Molefe,SIM-FSP-000004,BlueStar,Coastal Network,Western Cape,Active
4,SA-0000005,ADV000005,Grace Adams,SIM-FSP-000005,BLUESTAR,North Network,Limpopo,N
5,SA-0000006,ADV000006,Neo Smith,SIM-FSP-000006,Bank Assurance,NaN,Gauteng,Active
6,SA-0000007,ADV000007,Daniel Ndlovu,SIM-FSP-000007,BlueStar,Independent,Western Cape,Active
7,SA-0000008,ADV000008,Kabelo Smith,SIM-FSP-000008,Bank Assurance,Independent,North West,Y
8,SA-0000009,ADV000009,Lwazi Smith,SIM-FSP-000009,Bank-Assurance,North Network,North West,1
9,SA-0000010,ADV000010,David Mabena,SIM-FSP-000010,Bank Assurance,Coastal Network,Limpopo,N
10,SA-0000011,ADV000011,Brian Maseko,SIM-FSP-000011,Blue Star,NaN,KwaZulu-Natal,1
11,SA-0000012,ADV000012,Portia Khumalo,SIM-FSP-000012,Bank-Assurance,Independent,Eastern Cape,Y
12,SA-0000013,ADV000013,Zanele Khumalo,SIM-FSP-000013,NaN,North Network,Northern Cape,Yes
13,SA-0000014,ADV000014,Peter Maseko,SIM-FSP-000014,Blue Star,Coastal Network,Northern Cape,Active
14,SA-0000015,ADV000015,Fatima Mabena,SIM-FSP-000015,BLUESTAR,Coastal Network,Northern Cape,Active
15,SA-0000016,ADV000016,Brian Mthembu,SIM-FSP-000016,Blue Star,North Network,Limpopo,Active
16,SA-0000017,ADV000017,Daniel Smith,NaN,BLUESTAR,North Network,Western Cape,Y
17,SA-0000018,ADV000018,David Khumalo,SIM-FSP-000018,Bank-Assurance,Independent,Free State,1
18,SA-0000019,ADV000019,Lwazi Maseko,SIM-FSP-000019,Bank Assurance,Coastal Network,Mpumalanga,Y
19,SA-0000020,ADV000020,Nomsa van der Merwe,SIM-FSP-000020,Bank Assurance,Independent,Western Cape,Active

In [ ]:
advisor.info()

In [ ]:
advisor.shape

In [ ]:
advisor.isnull().sum()

In [ ]:
advisor[advisor['fsp_number'].isna()]

In [ ]:
# Create quarantine dataset
quarantine_fsp = advisor[advisor['fsp_number'].isna()]

# Remaining valid records
advisor_clean = advisor[advisor['fsp_number'].notna()]

In [ ]:
# Checking if the fsp number is correct quarantined number
print("Quarantined records:", len(quarantine_fsp))

In [ ]:
#Creating a new table for the quarantined fsp number
quarantine_fsp.to_csv("quarantine_fsp_number.csv", index=False)

In [ ]:
quarantine_fsp

In [19]:
# Quarantine records with missing fsp_number
quarantine_fsp = advisor[advisor['fsp_number'].isna()]

# Remove quarantined records from main dataset
advisor_clean = advisor[advisor['fsp_number'].notna()].copy()

In [ ]:
advisor_clean

In [ ]:
#Displayong the records after i quarantined the fsp number column
print("Original records:", len(advisor))
print("Quarantined records:", len(quarantine_fsp))
print("Remaining records:", len(advisor_clean))

In [25]:
advisor[advisor['channel'].isna()]

,source_row_id,advisor_id,advisor_name,fsp_number,channel,network_name,province,active_flag
12,SA-0000013,ADV000013,Zanele Khumalo,SIM-FSP-000013,NaN,North Network,Northern Cape,Yes
29,SA-0000030,ADV000030,David Molefe,SIM-FSP-000030,NaN,NaN,Western Cape,1
36,SA-0000037,ADV000037,Samuel Nkosi,SIM-FSP-000037,NaN,Independent,Gauteng,Y
81,SA-0000082,ADV000082,Ayanda Zulu,SIM-FSP-000082,NaN,Metro Group,Eastern Cape,Active
91,SA-0000092,ADV000092,Brian Mthembu,SIM-FSP-000092,NaN,Metro Group,Western Cape,Yes
108,SA-0000109,ADV000109,Grace Khumalo,SIM-FSP-000109,NaN,North Network,KwaZulu-Natal,N
114,SA-0000115,ADV000115,Mariam van der Merwe,SIM-FSP-000115,NaN,North Network,Free State,Active
189,SA-0000190,ADV000190,Keitumetse Maseko,SIM-FSP-000190,NaN,Metro Group,Gauteng,Active
211,SA-0000212,ADV000212,Nomsa Botha,SIM-FSP-000162,NaN,Independent,KwaZulu-Natal,Yes
250,SA-0000251,ADV000251,Daniel Mthembu,SIM-FSP-000251,NaN,Metro Group,Eastern Cape,Yes
294,SA-0000295,ADV000295,Sipho Jacobs,SIM-FSP-000295,NaN,Independent,Eastern Cape,1
329,SA-0000330,ADV000330,Amina Smith,SIM-FSP-000330,NaN,Independent,KwaZulu-Natal,N
354,SA-0000355,ADV000355,Thandi Smith,SIM-FSP-000355,NaN,North Network,Western Cape,Y
356,SA-0000357,ADV000357,Naledi Mahlangu,SIM-FSP-000357,NaN,Coastal Network,Northern Cape,1
401,SA-0000402,ADV000402,Grace Nkosi,SIM-FSP-000402,NaN,Coastal Network,Eastern Cape,Y
411,SA-0000412,ADV000412,Thandi Mahlangu,SIM-FSP-000412,NaN,North Network,KwaZulu-Natal,Y
421,SA-0000422,ADV000422,Musa Nkosi,NaN,NaN,North Network,Gauteng,Yes
454,SA-0000455,ADV000455,Mariam Maseko,SIM-FSP-000455,NaN,North Network,North West,Active
468,SA-0000469,ADV000469,Zanele Mokoena,SIM-FSP-000469,NaN,Independent,Limpopo,1
534,SA-0000535,ADV000535,Nomsa van der Merwe,SIM-FSP-000535,NaN,Independent,Gauteng,N
567,SA-0000568,ADV000568,Portia Ndlovu,SIM-FSP-000568,NaN,Metro Group,Mpumalanga,N
591,SA-0000592,ADV000592,Lerato Mabena,NaN,NaN,Coastal Network,Northern Cape,1

# Data Cleaning Two-Pot-Savings

In [5]:
import pandas as pd

two_pot_savings = pd.read_csv('../Data/sanlam_raw_two_pot_savings.csv')

two_pot_savings.head()

,source_row_id,account_id,client_id,policy_id,snapshot_date,savings_component,retirement_component,vested_component,reported_total_balance,withdrawal_amount,withdrawal_count_period,source_system
0,STP-000000001,RA-ACCOUNT-000000001,CL00005079,POL000019643,20/10/2024,"R 17,656.34","ZAR 724,310.93","568,425.33","ZAR 1,310,392.59",R 0.00,2,FundAdmin
1,STP-000000002,RA-ACCOUNT-000000002,CL00008089,POL000002536,2024-12-13,"R 171,682.07","ZAR 415,311.59","50,739.97","R 637,733.63",R 0.00,-1,RetirementCore
2,STP-000000003,RA-ACCOUNT-000000003,CL00005022,POL000024233,21/07/2025,"62.375,87","R 1,310,573.84","R 1,183,273.90","R 2,556,223.61","ZAR 20,833.32",0,FundAdmin
3,STP-000000004,RA-ACCOUNT-000000004,CL00006257,POL000002066,2025-06-08,65270.03,"R 15,727.94",1253083.21,"R 1,334,081.17","0,00",1,FundAdmin
4,STP-000000005,RA-ACCOUNT-000000005,CL00001746,POL000006008,23/10/2024,"ZAR 104,450.86",175954.41,1103712.56,"ZAR 1,384,117.83",0.00,-1,FundAdmin

In [6]:
two_pot_savings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   source_row_id            18000 non-null  object
 1   account_id               18000 non-null  object
 2   client_id                18000 non-null  object
 3   policy_id                18000 non-null  object
 4   snapshot_date            17959 non-null  object
 5   savings_component        17954 non-null  object
 6   retirement_component     17964 non-null  object
 7   vested_component         17950 non-null  object
 8   reported_total_balance   17928 non-null  object
 9   withdrawal_amount        17897 non-null  object
 10  withdrawal_count_period  18000 non-null  object
 11  source_system            18000 non-null  object
dtypes: object(12)
memory usage: 1.6+ MB

In [7]:
two_pot_savings.shape

(18000, 12)

In [8]:
two_pot_savings.isnull().sum()

source_row_id                0
account_id                   0
client_id                    0
policy_id                    0
snapshot_date               41
savings_component           46
retirement_component        36
vested_component            50
reported_total_balance      72
withdrawal_amount          103
withdrawal_count_period      0
source_system                0
dtype: int64