# Data Cleaning Advisor

In [150]:
import pandas as pd

advisor = pd.read_csv("../raw_data/sanlam_raw_advisors.csv")

In [ ]:
advisor.head(5)

In [ ]:
advisor.info()

In [ ]:
advisor.shape

In [ ]:
advisor.isnull().sum()

In [ ]:
# Checking  advisor_name
advisor[advisor['advisor_name'].isna()]

In [ ]:
advisor['advisor_name'].unique()

In [ ]:
# Load raw dataset
advisor_raw = pd.read_csv("../raw_data/sanlam_raw_advisors.csv")

# Create a copy for cleaning
advisor_clean = advisor_raw.copy()

In [187]:
# Quarantine missing fsp_number
quarantine_fsp = advisor[advisor['fsp_number'].isna()]

# Remove from clean dataset
advisor = advisor[advisor['fsp_number'].notna()].copy()

In [ ]:
# Checking if the fsp number is correct quarantined number
print("Quarantined records:", len(quarantine_fsp))

In [189]:
#Creating a new table for the quarantined fsp number
quarantine_fsp.to_csv("quarantine_fsp_number.csv", index=False)

In [ ]:
quarantine_fsp

In [ ]:
# Quarantine records with missing fsp_number
quarantine_fsp = advisor[advisor['fsp_number'].isna()]

# Remove quarantined records from main dataset
advisor = advisor[advisor['fsp_number'].notna()].copy()

In [ ]:
advisor_clean.to_csv("../clean_data/clean_advisors_data.csv", index=False)

In [ ]:
# Displayong the records after i quarantined the fsp number column
print("Original records:", len(advisor))
print("Quarantined records:", len(quarantine_fsp_number))
print("Remaining records:", len(advisor_clean))

In [ ]:
#Cleaning channel
advisor[advisor['channel'].isna()]

In [ ]:
advisor['channel'].unique()

In [ ]:
advisor['channel'].value_counts(dropna=False)

In [161]:
advisor['channel'] = advisor['channel'].str.strip().str.title()

advisor['channel'] = advisor['channel'].replace({
    'Bluestar': 'Blue Star',
    'Bank-Assurance': 'Bank Assurance'
})

In [178]:
advisor['channel'] = advisor['channel'].fillna('Not Recorded')

In [ ]:
#Cleaning network_name
advisor[advisor['network_name'].isna()]

In [ ]:
advisor['network_name'].unique()

In [182]:
advisor['network_name'] = advisor['network_name'].fillna('Not Recorded')

In [ ]:
#Cleaning province column
advisor[advisor['province'].isna()]

In [ ]:
advisor['province'].unique()

In [191]:
advisor.head(20)

,source_row_id,advisor_id,advisor_name,fsp_number,channel,network_name,province,active_flag
0,SA-0000001,ADV000001,Mariam Khumalo,SIM-FSP-000001,Bank Assurance,Metro Group,Gauteng,Active
1,SA-0000002,ADV000002,Fatima Khumalo,SIM-FSP-000002,Bank Assurance,Coastal Network,Northern Cape,Inactive
2,SA-0000003,ADV000003,Ayanda Ndlovu,SIM-FSP-000003,Bank Assurance,North Network,Limpopo,Inactive
3,SA-0000004,ADV000004,Ayanda Molefe,SIM-FSP-000004,Blue Star,Coastal Network,Western Cape,Active
4,SA-0000005,ADV000005,Grace Adams,SIM-FSP-000005,Blue Star,North Network,Limpopo,Inactive
5,SA-0000006,ADV000006,Neo Smith,SIM-FSP-000006,Bank Assurance,Not Recorded,Gauteng,Active
6,SA-0000007,ADV000007,Daniel Ndlovu,SIM-FSP-000007,Blue Star,Independent,Western Cape,Active
7,SA-0000008,ADV000008,Kabelo Smith,SIM-FSP-000008,Bank Assurance,Independent,North West,Active
8,SA-0000009,ADV000009,Lwazi Smith,SIM-FSP-000009,Bank Assurance,North Network,North West,Active
9,SA-0000010,ADV000010,David Mabena,SIM-FSP-000010,Bank Assurance,Coastal Network,Limpopo,Inactive
10,SA-0000011,ADV000011,Brian Maseko,SIM-FSP-000011,Blue Star,Not Recorded,KwaZulu-Natal,Active
11,SA-0000012,ADV000012,Portia Khumalo,SIM-FSP-000012,Bank Assurance,Independent,Eastern Cape,Active
12,SA-0000013,ADV000013,Zanele Khumalo,SIM-FSP-000013,Not Recorded,North Network,Northern Cape,Active
13,SA-0000014,ADV000014,Peter Maseko,SIM-FSP-000014,Blue Star,Coastal Network,Northern Cape,Active
14,SA-0000015,ADV000015,Fatima Mabena,SIM-FSP-000015,Blue Star,Coastal Network,Northern Cape,Active
15,SA-0000016,ADV000016,Brian Mthembu,SIM-FSP-000016,Blue Star,North Network,Limpopo,Active
17,SA-0000018,ADV000018,David Khumalo,SIM-FSP-000018,Bank Assurance,Independent,Free State,Active
18,SA-0000019,ADV000019,Lwazi Maseko,SIM-FSP-000019,Bank Assurance,Coastal Network,Mpumalanga,Active
19,SA-0000020,ADV000020,Nomsa van der Merwe,SIM-FSP-000020,Bank Assurance,Independent,Western Cape,Active
20,SA-0000021,ADV000021,Neo Sithole,SIM-FSP-000021,Blue Star,North Network,Eastern Cape,Inactive

In [ ]:
#Cleaning active flag column
advisor[advisor['active_flag'].isna()]

In [ ]:
advisor['active_flag'].unique()

In [170]:
advisor['active_flag'] = advisor['active_flag'].replace({
    '1': 'Active',
    'Y': 'Active',
    'Yes': 'Active',
    'N': 'Inactive'
})

In [ ]:
advisor['active_flag'].value_counts(dropna=False)

In [173]:
advisor.duplicated().sum()

np.int64(0)

In [ ]:
advisor

# Data Cleaning Two-Pot-Savings

In [ ]:
import pandas as pd

two_pot_savings_clean = pd.read_csv('../raw_data/sanlam_raw_two_pot_savings.csv')

two_pot_savings_clean

In [ ]:
two_pot_savings_clean.head()

,source_row_id,account_id,client_id,policy_id,snapshot_date,savings_component,retirement_component,vested_component,reported_total_balance,withdrawal_amount,withdrawal_count_period,source_system
0,STP-000000001,RA-ACCOUNT-000000001,CL00005079,POL000019643,20/10/2024,"R 17,656.34","ZAR 724,310.93","568,425.33","ZAR 1,310,392.59",R 0.00,2,FundAdmin
1,STP-000000002,RA-ACCOUNT-000000002,CL00008089,POL000002536,2024-12-13,"R 171,682.07","ZAR 415,311.59","50,739.97","R 637,733.63",R 0.00,-1,RetirementCore
2,STP-000000003,RA-ACCOUNT-000000003,CL00005022,POL000024233,21/07/2025,"62.375,87","R 1,310,573.84","R 1,183,273.90","R 2,556,223.61","ZAR 20,833.32",0,FundAdmin
3,STP-000000004,RA-ACCOUNT-000000004,CL00006257,POL000002066,2025-06-08,65270.03,"R 15,727.94",1253083.21,"R 1,334,081.17","0,00",1,FundAdmin
4,STP-000000005,RA-ACCOUNT-000000005,CL00001746,POL000006008,23/10/2024,"ZAR 104,450.86",175954.41,1103712.56,"ZAR 1,384,117.83",0.00,-1,FundAdmin

In [220]:
two_pot_savings_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17842 entries, 0 to 17999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   source_row_id            17842 non-null  object
 1   account_id               17842 non-null  object
 2   client_id                17842 non-null  object
 3   policy_id                17842 non-null  object
 4   snapshot_date            17842 non-null  object
 5   savings_component        17754 non-null  float64
 6   retirement_component     17755 non-null  float64
 7   vested_component         17748 non-null  float64
 8   reported_total_balance   17701 non-null  float64
 9   withdrawal_amount        17643 non-null  float64
 10  withdrawal_count_period  17842 non-null  int64
 11  source_system            17842 non-null  object
 12  balance_flag             17842 non-null  object
dtypes: float64(5), int64(1), object(7)
memory usage: 1.9+ MB

In [225]:
two_pot_savings_clean.shape

(17842, 13)

In [221]:
two_pot_savings_clean.isnull().sum()

source_row_id                0
account_id                   0
client_id                    0
policy_id                    0
snapshot_date                0
savings_component           88
retirement_component        87
vested_component            94
reported_total_balance     141
withdrawal_amount          199
withdrawal_count_period      0
source_system                0
balance_flag                 0
dtype: int64

In [ ]:
# Cleaning the date format 
two_pot_savings_clean[two_pot_savings_clean['snapshot_date'].isna()].head(50)

In [ ]:
two_pot_savings_clean['snapshot_date'].unique()

In [ ]:
bad_dates = two_pot_savings_clean.loc[
    pd.to_datetime(
        two_pot_savings_clean['snapshot_date'],
        errors='coerce',
        format='mixed'
    ).isna(),
    'snapshot_date'
]

bad_dates.value_counts(dropna=False)

snapshot_date
31/31/2024    51
NaN           41
2024-19-42    35
not-a-date    31
Name: count, dtype: int64

In [ ]:
missing_dates = two_pot_savings_clean[
    two_pot_savings_clean['snapshot_date'].isna()
].copy()

missing_dates['quarantine_reason'] = 'Missing Date'

In [ ]:
missing_dates

In [ ]:
test_dates = pd.to_datetime(
    two_pot_savings_clean['snapshot_date'],
    errors='coerce',
    format='mixed'
)

invalid_dates = two_pot_savings_clean[
    test_dates.isna() &
    two_pot_savings_clean['snapshot_date'].notna()
].copy()

invalid_dates['quarantine_reason'] = 'Invalid Date'

In [ ]:
invalid_dates

In [54]:
quarantine_snapshot_date = pd.concat(
    [missing_dates, invalid_dates],
    ignore_index=True
)

In [227]:
quarantine_snapshot_date['quarantine_reason'].value_counts()

quarantine_reason
Invalid Date    117
Missing Date     41
Name: count, dtype: int64

In [57]:
quarantine_snapshot_date.to_csv(
    "../quarantine/quarantine_snapshot_date.csv",
    index=False
)

In [ ]:
two_pot_savings_clean = two_pot_savings_clean[
    test_dates.notna()
].copy()

In [ ]:
quarantine_snapshot_date = two_pot_savings_clean[
    two_pot_savings_clean['snapshot_date'].isna()
].copy()

In [ ]:
test_dates = pd.to_datetime(
    two_pot_savings_clean['snapshot_date'],
    errors='coerce',
    format='mixed'
)

print(test_dates.isna().sum())

158

In [69]:
two_pot_savings_clean['snapshot_date'] = pd.to_datetime(
    two_pot_savings_clean['snapshot_date'],
    format='mixed'
)

In [70]:
two_pot_savings_clean['snapshot_date'].dtype

dtype('<M8[ns]')

In [75]:
two_pot_savings_clean['snapshot_date'] = (
    two_pot_savings_clean['snapshot_date']
    .dt.strftime('%d-%m-%Y')
)

In [ ]:
two_pot_savings_clean

In [ ]:
# Cleaning Savings Component 
two_pot_savings_clean[two_pot_savings_clean['savings_component'].isna()]

In [213]:
two_pot_savings_clean['savings_component'].unique()

array([ 17656.34, 171682.07,  62375.87, ...,  13244.54, 139256.04,
       156607.05], shape=(17747,))

In [212]:
two_pot_savings_clean['savings_component'].sample(20)

1602     47608.78
5213    113569.43
6740     30598.96
11604   134676.90
13240   131868.43
12678    37227.00
15995     6017.93
1656     54074.53
1996    104883.99
6401      4396.91
14697    90574.13
827       3480.60
3323    165123.36
10594   167262.23
785     128998.89
13252    63229.71
8068     28756.81
189      38480.01
11988   136471.22
1728    -57025.00
Name: savings_component, dtype: float64

In [211]:
two_pot_savings_clean['savings_component'].apply(type).value_counts()

savings_component
<class 'float'>    17842
Name: count, dtype: int64

In [83]:
two_pot_savings_clean['savings_component'].str.contains(
    '[A-Za-z]',
    na=False,
    regex=True
).sum()

np.int64(7151)

In [84]:
two_pot_savings_clean['savings_component'] = two_pot_savings_clean['savings_component'].replace({
    'not recorded': pd.NA
})

In [85]:
two_pot_savings_clean['savings_component'] = (
    two_pot_savings_clean['savings_component']
    .str.strip()
    .str.replace('R', '', regex=False)
    .str.replace('ZAR', '', regex=False)
    .str.replace('zar', '', regex=False)
    .str.replace('ZA', '', regex=False)
    .str.strip()
)

In [86]:
two_pot_savings_clean['savings_component'].str.contains(
    r'\.\d{3},',
    regex=True,
    na=False
).sum()

np.int64(3526)

In [89]:
two_pot_savings_clean[
    two_pot_savings_clean['savings_component'].str.contains(r'\(', na=False)
]['savings_component'].head()

Series([], Name: savings_component, dtype: object)

In [88]:
two_pot_savings_clean['savings_component'] = (
    two_pot_savings_clean['savings_component']
    .str.replace('(', '', regex=False)
    .str.replace(')', '', regex=False)
)

In [ ]:
two_pot_savings_clean[
    two_pot_savings_clean['savings_component'].str.contains('--', na=False)
]['savings_component'].head()

In [91]:
import numpy as np

two_pot_savings_clean['savings_component'] = (
    two_pot_savings_clean['savings_component']
    .replace('--', np.nan)
)

In [93]:
mask = two_pot_savings_clean['savings_component'].str.contains(
    r'\.\d{3},\d{2}', na=False
)
 
two_pot_savings_clean.loc[mask, 'savings_component'] = (
    two_pot_savings_clean.loc[mask, 'savings_component']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
)
 
two_pot_savings_clean['savings_component'] = (
    two_pot_savings_clean['savings_component']
    .str.replace(',', '', regex=False)
)

In [ ]:
two_pot_savings_clean['savings_component'] = pd.to_numeric(
    two_pot_savings_clean['savings_component'],
    errors='coerce'
)

In [ ]:
test_amounts = pd.to_numeric(
    two_pot_savings_clean['savings_component'],
    errors='coerce'
)

bad_rows = two_pot_savings_clean[
    test_amounts.isna() &
    two_pot_savings['savings_component'].notna()
]

bad_rows['savings_component'].value_counts(dropna=False)

In [196]:
pd.options.display.float_format = '{:.2f}'.format

In [ ]:
two_pot_savings_clean.info()

In [209]:
two_pot_savings_clean['savings_component'].isin([
    'N/A',
    'NULL',
    'Not Recorded',
    'R --',
    '--'
]).sum()

np.int64(0)

In [96]:
two_pot_savings_clean['savings_component'] = pd.to_numeric(
    two_pot_savings_clean['savings_component'],
    errors='coerce'
)

In [ ]:
# Cleaning retirement component
two_pot_savings_clean[two_pot_savings_clean['retirement_component'].isna()]

In [ ]:
two_pot_savings_clean['retirement_component'].unique()

In [195]:
two_pot_savings_clean[
    two_pot_savings_clean['retirement_component']
    .astype(str)
    .str.contains('[A-Za-z]', na=False)
]['retirement_component'].value_counts(dropna=False)

retirement_component
NaN    87
Name: count, dtype: int64

In [101]:
two_pot_savings_clean['retirement_component'] = (
    two_pot_savings_clean['retirement_component']
    .replace({
        'not recorded': pd.NA,
        'R --': pd.NA
    })
)

In [103]:
two_pot_savings_clean['retirement_component'] = (
    two_pot_savings_clean['retirement_component']
    .str.strip()
    .str.replace('R', '', regex=False)
    .str.replace('ZAR', '', regex=False)
    .str.replace('zar', '', regex=False)
    .str.replace('ZA', '', regex=False)
    .str.strip()
)

In [ ]:
two_pot_savings_clean[
    two_pot_savings_clean['retirement_component'].str.contains(r'\(', na=False)
]['retirement_component'].head()

In [105]:
mask = two_pot_savings_clean['retirement_component'].str.contains(
    r'\.\d{3},\d{2}', na=False
)
 
two_pot_savings_clean.loc[mask, 'retirement_component'] = (
    two_pot_savings_clean.loc[mask, 'retirement_component']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
)
 
two_pot_savings_clean['retirement_component'] = (
    two_pot_savings_clean['retirement_component']
    .str.replace(',', '', regex=False)
)

In [106]:
two_pot_savings_clean['retirement_component'] = pd.to_numeric(
    two_pot_savings_clean['retirement_component'],
    errors='coerce'
)

In [ ]:
# Cleaning Vested Component
two_pot_savings_clean[two_pot_savings_clean['vested_component'].isna()]

In [208]:
two_pot_savings_clean['vested_component'].unique()

array([ 568425.33,   50739.97, 1183273.9 , ..., 1697718.43,  109149.7 ,
        348260.94], shape=(17749,))

In [207]:
two_pot_savings_clean[
    two_pot_savings_clean['vested_component']
    .astype(str)
    .str.contains('[A-Za-z]', na=False)
]['vested_component'].value_counts(dropna=False)

vested_component
NaN    94
Name: count, dtype: int64

In [110]:
two_pot_savings_clean['vested_component'] = (
    two_pot_savings_clean['vested_component']
    .replace({
        'not recorded': pd.NA,
        'R --': pd.NA
    })
)

In [111]:
two_pot_savings_clean['vested_component'] = (
    two_pot_savings_clean['vested_component']
    .str.strip()
    .str.replace('R', '', regex=False)
    .str.replace('ZAR', '', regex=False)
    .str.replace('zar', '', regex=False)
    .str.replace('ZA', '', regex=False)
    .str.strip()
)

In [112]:
mask = two_pot_savings_clean['vested_component'].str.contains(
    r'\.\d{3},\d{2}', na=False
)
 
two_pot_savings_clean.loc[mask, 'vested_component'] = (
    two_pot_savings_clean.loc[mask, 'vested_component']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
)
 
two_pot_savings_clean['vested_component'] = (
    two_pot_savings_clean['vested_component']
    .str.replace(',', '', regex=False)
)

In [113]:
two_pot_savings_clean['vested_component'] = pd.to_numeric(
    two_pot_savings_clean['vested_component'],
    errors='coerce'
)

In [228]:
two_pot_savings_clean.head()

,source_row_id,account_id,client_id,policy_id,snapshot_date,savings_component,retirement_component,vested_component,reported_total_balance,withdrawal_amount,withdrawal_count_period,source_system,balance_flag
0,STP-000000001,RA-ACCOUNT-000000001,CL00005079,POL000019643,20-10-2024,17656.34,724310.93,568425.33,1310392.59,0.00,2,FundAdmin,Mismatch
1,STP-000000002,RA-ACCOUNT-000000002,CL00008089,POL000002536,13-12-2024,171682.07,415311.59,50739.97,637733.63,0.00,1,RetirementCore,Match
2,STP-000000003,RA-ACCOUNT-000000003,CL00005022,POL000024233,21-07-2025,62375.87,1310573.84,1183273.90,2556223.61,20833.32,0,FundAdmin,Match
3,STP-000000004,RA-ACCOUNT-000000004,CL00006257,POL000002066,08-06-2025,65270.03,15727.94,1253083.21,1334081.17,0.00,1,FundAdmin,Mismatch
4,STP-000000005,RA-ACCOUNT-000000005,CL00001746,POL000006008,23-10-2024,104450.86,175954.41,1103712.56,1384117.83,0.00,1,FundAdmin,Match

In [ ]:
#Cleaning Reported total balance 
two_pot_savings_clean[two_pot_savings_clean['reported_total_balance'].isna()]

In [ ]:
two_pot_savings_clean['reported_total_balance'].unique()

In [ ]:
two_pot_savings_clean[
    two_pot_savings_clean['reported_total_balance']
    .astype(str)
    .str.contains('[A-Za-z]', na=False)
]['reported_total_balance'].value_counts(dropna=False)

In [116]:
two_pot_savings_clean['reported_total_balance'] = (
    two_pot_savings_clean['reported_total_balance']
    .replace({
        'not recorded': pd.NA,
        'R --': pd.NA
    })
)

In [117]:
two_pot_savings_clean['reported_total_balance'] = (
    two_pot_savings_clean['reported_total_balance']
    .str.strip()
    .str.replace('R', '', regex=False)
    .str.replace('ZAR', '', regex=False)
    .str.replace('zar', '', regex=False)
    .str.replace('ZA', '', regex=False)
    .str.strip()
)

In [118]:
mask = two_pot_savings_clean['reported_total_balance'].str.contains(
    r'\.\d{3},\d{2}', na=False
)
 
two_pot_savings_clean.loc[mask, 'reported_total_balance'] = (
    two_pot_savings_clean.loc[mask, 'reported_total_balance']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
)
 
two_pot_savings_clean['reported_total_balance'] = (
    two_pot_savings_clean['reported_total_balance']
    .str.replace(',', '', regex=False)
)

In [119]:
two_pot_savings_clean['reported_total_balance'] = pd.to_numeric(
    two_pot_savings_clean['reported_total_balance'],
    errors='coerce'
)

In [ ]:
# Cleaning Withdrawal Amount
two_pot_savings_clean[two_pot_savings_clean['withdrawal_amount'].isna()]

In [ ]:
two_pot_savings_clean['withdrawal_amount'].unique()

In [ ]:
two_pot_savings_clean[
    two_pot_savings_clean['withdrawal_amount']
    .astype(str)
    .str.contains('[A-Za-z]', na=False)
]['withdrawal_amount'].value_counts(dropna=False)

In [122]:
two_pot_savings_clean['withdrawal_amount'] = (
    two_pot_savings_clean['withdrawal_amount']
    .replace({
        'not recorded': pd.NA,
        'R --': pd.NA
    })
)

In [124]:
two_pot_savings_clean['withdrawal_amount'] = (
    two_pot_savings_clean['withdrawal_amount']
    .str.strip()
    .str.replace('R', '', regex=False)
    .str.replace('ZAR', '', regex=False)
    .str.replace('zar', '', regex=False)
    .str.replace('ZA', '', regex=False)
    .str.strip()
)

In [125]:
mask = two_pot_savings_clean['withdrawal_amount'].str.contains(
    r'\.\d{3},\d{2}', na=False
)
 
two_pot_savings_clean.loc[mask, 'withdrawal_amount'] = (
    two_pot_savings_clean.loc[mask, 'withdrawal_amount']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
)
 
two_pot_savings_clean['withdrawal_amount'] = (
    two_pot_savings_clean['withdrawal_amount']
    .str.replace(',', '', regex=False)
)

In [126]:
two_pot_savings_clean['withdrawal_amount'] = pd.to_numeric(
    two_pot_savings_clean['withdrawal_amount'],
    errors='coerce'
)

In [ ]:
# Cleaning Withdrawal count period
two_pot_savings_clean[two_pot_savings_clean['withdrawal_count_period'].isna()]

In [ ]:
two_pot_savings_clean['withdrawal_count_period'].unique()

In [ ]:
two_pot_savings_clean.withdrawal_count_period.value_counts()

In [128]:
two_pot_savings_clean['withdrawal_count_period'] = (
    two_pot_savings_clean['withdrawal_count_period']
    .replace('one', '1')
)

In [129]:
two_pot_savings_clean['withdrawal_count_period'] = (
    two_pot_savings_clean['withdrawal_count_period']
    .replace('-1', '1')
)

In [130]:
two_pot_savings_clean['withdrawal_count_period'] = (
    two_pot_savings_clean['withdrawal_count_period']
    .astype('int64')
)

In [ ]:
# Cleaing the source systm
two_pot_savings_clean[two_pot_savings_clean['source_system'].isna()]

In [ ]:
two_pot_savings_clean['source_system'].unique()

In [132]:
# Calculate the correct balance
corresponded_balance = (
    two_pot_savings_clean['savings_component']
    + two_pot_savings_clean['retirement_component']
    + two_pot_savings_clean['vested_component']
)

# Create a flag column
two_pot_savings_clean['balance_flag'] = np.where(
    abs(corresponded_balance - two_pot_savings_clean['reported_total_balance']) > 0.01,
    'Mismatch',
    'Match'
)

In [204]:
two_pot_savings_clean['balance_flag'].value_counts()

balance_flag
Match       10520
Mismatch     7322
Name: count, dtype: int64

In [230]:
two_pot_savings_clean

,source_row_id,account_id,client_id,policy_id,snapshot_date,savings_component,retirement_component,vested_component,reported_total_balance,withdrawal_amount,withdrawal_count_period,source_system,balance_flag,withdrawal_flag
0,STP-000000001,RA-ACCOUNT-000000001,CL00005079,POL000019643,20-10-2024,17656.34,724310.93,568425.33,1310392.59,0.00,2,FundAdmin,Mismatch,Invalid
1,STP-000000002,RA-ACCOUNT-000000002,CL00008089,POL000002536,13-12-2024,171682.07,415311.59,50739.97,637733.63,0.00,1,RetirementCore,Match,Invalid
2,STP-000000003,RA-ACCOUNT-000000003,CL00005022,POL000024233,21-07-2025,62375.87,1310573.84,1183273.90,2556223.61,20833.32,0,FundAdmin,Match,Invalid
3,STP-000000004,RA-ACCOUNT-000000004,CL00006257,POL000002066,08-06-2025,65270.03,15727.94,1253083.21,1334081.17,0.00,1,FundAdmin,Mismatch,Invalid
4,STP-000000005,RA-ACCOUNT-000000005,CL00001746,POL000006008,23-10-2024,104450.86,175954.41,1103712.56,1384117.83,0.00,1,FundAdmin,Match,Invalid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,STP-000017996,RA-ACCOUNT-000017996,CL00001554,POL000009455,22-10-2025,65053.55,167022.46,729504.41,961580.43,114212.44,2,FundAdmin,Mismatch,Valid
17996,STP-000017997,RA-ACCOUNT-000017997,CL00010268,POL000018330,14-09-2024,166226.72,1254501.84,1697718.43,3118446.99,7316.02,3,TwoPotMigration,Match,Valid
17997,STP-000017998,RA-ACCOUNT-000017998,CL00007193,POL000016585,11-05-2025,13244.54,1280740.71,109149.70,1403134.95,0.00,3,FundAdmin,Match,Invalid
17998,STP-000017999,RA-ACCOUNT-000017999,CL00006353,POL000021923,13-03-2025,139256.04,146128.86,348260.94,633645.83,0.00,1,FundAdmin,Mismatch,Invalid
17999,STP-000018000,RA-ACCOUNT-000018000,CL00009807,POL000024243,16-10-2025,156607.05,757118.46,NaN,2263764.27,0.00,1,RetirementCore,Mismatch,Invalid

In [202]:
calculated_balance = (
    two_pot_savings_clean['savings_component']
    + two_pot_savings_clean['retirement_component']
    + two_pot_savings_clean['vested_component']
)

two_pot_savings_clean['balance_flag'] = np.where(
    np.round(calculated_balance, 2)
    == np.round(two_pot_savings_clean['reported_total_balance'], 2),
    'Match',
    'Mismatch'
)

In [206]:
two_pot_savings_clean.duplicated().sum()

np.int64(0)

In [229]:
two_pot_savings_clean['withdrawal_flag'] = np.where(
    (
        (two_pot_savings_clean['withdrawal_amount'] == 0)
        & (two_pot_savings_clean['withdrawal_count_period'] > 0)
    )
    |
    (
        (two_pot_savings_clean['withdrawal_amount'] > 0)
        & (two_pot_savings_clean['withdrawal_count_period'] == 0)
    ),
    'Invalid',
    'Valid'
)

In [231]:
two_pot_savings_clean['withdrawal_flag'].value_counts()

withdrawal_flag
Invalid    11334
Valid       6508
Name: count, dtype: int64

In [237]:
negative_amounts = two_pot_savings_clean[
    (two_pot_savings_clean['savings_component'] < 0) |
    (two_pot_savings_clean['retirement_component'] < 0) |
    (two_pot_savings_clean['vested_component'] < 0) |
    (two_pot_savings_clean['reported_total_balance'] < 0) |
    (two_pot_savings_clean['withdrawal_amount'] < 0)
]

negative_amounts

,source_row_id,account_id,client_id,policy_id,snapshot_date,savings_component,retirement_component,vested_component,reported_total_balance,withdrawal_amount,withdrawal_count_period,source_system,balance_flag,withdrawal_flag
13,STP-000000014,RA-ACCOUNT-000000014,CL00010994,POL000004667,13-07-2025,-104676.63,892273.54,603691.68,1600641.85,25851.07,1,TwoPotMigration,Mismatch,Valid
60,STP-000000061,RA-ACCOUNT-000000061,CL00008162,POL000007590,16-06-2025,-329.32,640725.53,1008592.90,1649647.75,0.00,3,FundAdmin,Mismatch,Invalid
70,STP-000000071,RA-ACCOUNT-000000071,CL00003719,POL000012670,18-09-2024,-117506.71,85193.49,760871.37,963571.57,0.00,1,TwoPotMigration,Mismatch,Invalid
94,STP-000000095,RA-ACCOUNT-000000095,CL00000831,POL000017647,15-08-2025,-130094.25,1387582.99,1713256.58,3230933.83,0.00,1,RetirementCore,Mismatch,Invalid
102,STP-000000103,RA-ACCOUNT-000000103,CL00010850,POL000001859,05-04-2025,-3579.69,712826.73,1634967.69,2351374.11,0.00,2,FundAdmin,Mismatch,Invalid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17851,STP-000017852,RA-ACCOUNT-000017852,CL00003712,POL000021492,03-09-2025,-75553.59,752377.27,1292255.54,2120186.41,0.00,1,RetirementCore,Mismatch,Invalid
17867,STP-000017868,RA-ACCOUNT-000017868,CL00009935,POL000005691,30-11-2025,-14123.12,731922.45,100714.77,846760.34,0.00,1,RetirementCore,Mismatch,Invalid
17902,STP-000017903,RA-ACCOUNT-000017903,CL00003388,POL000025577,26-06-2025,-2758.72,284135.89,1005758.30,1292652.90,0.00,0,RetirementCore,Mismatch,Valid
17908,STP-000017909,RA-ACCOUNT-000017909,CL00004156,POL000018799,05-09-2024,-5705.09,195992.59,1513830.75,1715528.43,0.00,1,FundAdmin,Mismatch,Invalid
17935,STP-000017936,RA-ACCOUNT-000017936,CL00003524,POL000015597,19-10-2024,-137849.55,803527.46,1662581.90,2603958.91,21921.12,1,RetirementCore,Mismatch,Valid

In [234]:
negative_amounts.shape[0]

320

In [238]:
two_pot_savings_clean.to_csv("../clean_data/clean_two_pot_savings_data.csv", index=False)